-- =============================================================================
-- legacy_java_bank.sql - Heritage Payments relational schema
-- Referenced by: AccountService, FundsTransferProcessor, LedgerPostingDao,
--                EndOfDaySettlementJob
-- =============================================================================

CREATE TABLE CUSTOMER (
    CUSTOMER_ID          BIGINT          NOT NULL,
    CUSTOMER_NUMBER      VARCHAR(20)     NOT NULL,
    FULL_NAME            VARCHAR(120)    NOT NULL,
    RISK_RATING          VARCHAR(12)     NOT NULL,
    KYC_STATUS           VARCHAR(12)     NOT NULL,
    CREATED_AT           TIMESTAMP       NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UQ_CUSTOMER_NUMBER UNIQUE (CUSTOMER_NUMBER)
);

CREATE TABLE ACCOUNT (
    ACCOUNT_ID              BIGINT          NOT NULL,
    CUSTOMER_ID             BIGINT          NOT NULL,
    ACCOUNT_NUMBER          VARCHAR(20)     NOT NULL,
    ACCOUNT_TYPE            VARCHAR(20)     NOT NULL,
    STATUS                  VARCHAR(12)     NOT NULL,
    BALANCE                 DECIMAL(17,2)   NOT NULL DEFAULT 0.00,
    LAST_POSTED_REFERENCE   VARCHAR(40),
    OPENED_AT               TIMESTAMP       NOT NULL,
    CLOSED_AT               TIMESTAMP,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT UQ_ACCOUNT_NUMBER UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE DAILY_LIMIT (
    DAILY_LIMIT_ID       BIGINT          NOT NULL,
    CUSTOMER_ID          BIGINT          NOT NULL,
    BUSINESS_DATE        DATE            NOT NULL,
    DAILY_LIMIT_AMOUNT   DECIMAL(17,2)   NOT NULL,
    USED_AMOUNT          DECIMAL(17,2)   NOT NULL DEFAULT 0.00,
    UPDATED_AT           TIMESTAMP       NOT NULL,
    CONSTRAINT PK_DAILY_LIMIT PRIMARY KEY (DAILY_LIMIT_ID),
    CONSTRAINT UQ_DAILY_LIMIT_CUSTOMER_DATE UNIQUE (CUSTOMER_ID, BUSINESS_DATE),
    CONSTRAINT FK_DAILY_LIMIT_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TRANSFER_REQUEST (
    TRANSFER_REQUEST_ID           BIGINT          NOT NULL,
    CUSTOMER_ID                   BIGINT          NOT NULL,
    DEBIT_ACCOUNT_ID              BIGINT          NOT NULL,
    CREDIT_ACCOUNT_ID             BIGINT,
    SETTLEMENT_SUSPENSE_ACCOUNT_ID BIGINT         NOT NULL,
    AMOUNT                        DECIMAL(17,2)   NOT NULL,
    SAME_BANK_TRANSFER            SMALLINT        NOT NULL,
    EXTERNAL_ROUTING_NUMBER       VARCHAR(9),
    STATUS                        VARCHAR(12)     NOT NULL,
    REQUESTED_AT                  TIMESTAMP       NOT NULL,
    SETTLEMENT_DATE               DATE,
    CONSTRAINT PK_TRANSFER_REQUEST PRIMARY KEY (TRANSFER_REQUEST_ID),
    CONSTRAINT FK_TRANSFER_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_TRANSFER_DEBIT_ACCOUNT FOREIGN KEY (DEBIT_ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_TRANSFER_CREDIT_ACCOUNT FOREIGN KEY (CREDIT_ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_TRANSFER_SUSPENSE_ACCOUNT FOREIGN KEY (SETTLEMENT_SUSPENSE_ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE LEDGER_ENTRY (
    LEDGER_ENTRY_ID       BIGINT          NOT NULL,
    TRANSFER_REQUEST_ID   BIGINT          NOT NULL,
    ACCOUNT_ID            BIGINT          NOT NULL,
    ENTRY_TYPE            VARCHAR(8)      NOT NULL,
    AMOUNT                DECIMAL(17,2)   NOT NULL,
    NARRATIVE             VARCHAR(200)    NOT NULL,
    POSTED_AT             TIMESTAMP       NOT NULL,
    CONSTRAINT PK_LEDGER_ENTRY PRIMARY KEY (LEDGER_ENTRY_ID),
    CONSTRAINT FK_LEDGER_TRANSFER FOREIGN KEY (TRANSFER_REQUEST_ID)
        REFERENCES TRANSFER_REQUEST(TRANSFER_REQUEST_ID),
    CONSTRAINT FK_LEDGER_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE RISK_HOLD (
    RISK_HOLD_ID          BIGINT          NOT NULL,
    CUSTOMER_ID           BIGINT          NOT NULL,
    ACCOUNT_ID            BIGINT          NOT NULL,
    TRANSFER_REQUEST_ID   BIGINT          NOT NULL,
    REASON_CODE           VARCHAR(40)     NOT NULL,
    HOLD_AMOUNT           DECIMAL(17,2)   NOT NULL,
    CREATED_AT            TIMESTAMP       NOT NULL,
    RELEASED_AT           TIMESTAMP,
    CONSTRAINT PK_RISK_HOLD PRIMARY KEY (RISK_HOLD_ID),
    CONSTRAINT FK_RISK_HOLD_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_RISK_HOLD_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_RISK_HOLD_TRANSFER FOREIGN KEY (TRANSFER_REQUEST_ID)
        REFERENCES TRANSFER_REQUEST(TRANSFER_REQUEST_ID)
);

CREATE TABLE SETTLEMENT_AUDIT (
    SETTLEMENT_AUDIT_ID   BIGINT          NOT NULL,
    BUSINESS_DATE         DATE            NOT NULL,
    SETTLED_COUNT         INTEGER         NOT NULL,
    SETTLED_AMOUNT        DECIMAL(17,2)   NOT NULL,
    STATUS                VARCHAR(12)     NOT NULL,
    FAILURE_REASON        VARCHAR(500),
    CREATED_AT            TIMESTAMP       NOT NULL,
    CONSTRAINT PK_SETTLEMENT_AUDIT PRIMARY KEY (SETTLEMENT_AUDIT_ID)
);
