"""
models/chunk.py — Migration chunk and its validation result models.

A MigrationChunk is one logical unit of work: a function, paragraph, section,
or class extracted from the legacy source that will be individually:
  1. Statically analysed (Layer 1)
  2. AI-reviewed (Layer 2)
  3. Test-generated-and-run (Layer 3)
  4. Presented to a human for approval

Chunking strategy (not implemented in the skeleton) should balance:
  - Chunk small enough to fit in the LLM context window
  - Chunk large enough to preserve business logic coherence
  - Keep a chunk aligned to a COBOL SECTION or PARAGRAPH boundary

Pipeline position:
  MigrationChunks are created by core/pipeline.py after Layer 0 completes.
  They flow through layers 1 → 2 → 3, then await human approval.
  All chunks must be Approved before Layer 4 runs.
"""

from __future__ import annotations

import uuid
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class RiskLevel(str, Enum):
    """Risk level assigned to a chunk based on Layer 0 risk scorer output."""
    LOW    = "Low"
    MEDIUM = "Medium"
    HIGH   = "High"
    CRITICAL = "Critical"


class ChunkStatus(str, Enum):
    """Human-approval lifecycle state of a migration chunk."""
    PENDING  = "Pending"   # Waiting to enter the pipeline
    RUNNING  = "Running"   # Currently being processed
    REVIEW   = "Review"    # Awaiting human approval
    APPROVED = "Approved"  # Human signed off — ready for Layer 4
    REJECTED = "Rejected"  # Human sent it back — needs rework


# ---------------------------------------------------------------------------
# TestResult
# ---------------------------------------------------------------------------

class TestResult(BaseModel):
    """
    Result of a single auto-generated test case for a migrated chunk.

    Generated by core/layer3/test_generator.py and run via pytest.
    """

    name: str
    """Test function name, e.g. 'test_interest_calc_tier1_boundary'."""

    passed: bool
    """True if the test passed, False if it failed or errored."""

    error_message: Optional[str] = None
    """Pytest output if the test failed. None if passed."""

    duration_ms: float = 0.0
    """How long the test took to run in milliseconds."""

    # TODO (test_generator.py): add generated_prompt field so devs can
    # inspect what the LLM was asked to generate for debugging.


# ---------------------------------------------------------------------------
# StaticAnalysisResult
# ---------------------------------------------------------------------------

class StaticAnalysisResult(BaseModel):
    """
    Output of Layer 1 (core/layer1/static_analyser.py) for a single chunk.

    Layer 1 uses rule-based checks (no LLM) to catch obvious problems in the
    generated Python before wasting tokens on an LLM review:
      - Syntax errors
      - Undefined variable references
      - Type annotation completeness
      - Complexity metrics (cyclomatic complexity, line count)
    """

    passed: bool = False
    """True if all static checks passed. False triggers a retry."""

    issues: list[str] = Field(default_factory=list)
    """
    Human-readable list of issues found, e.g.:
      ['SyntaxError at line 12: unexpected indent',
       'Variable "balance" referenced before assignment']
    """

    complexity_score: float = 0.0
    """
    Cyclomatic complexity of the migrated code.
    TODO (static_analyser.py): use radon or ast.parse to calculate this.
    """

    line_count: int = 0
    """Line count of the migrated chunk (excluding blanks and comments)."""

    # TODO (static_analyser.py): add linting_output: str for raw flake8/pylint


# ---------------------------------------------------------------------------
# AIReviewResult
# ---------------------------------------------------------------------------

class AIReviewResult(BaseModel):
    """
    Output of Layer 2 (core/layer2/ai_reviewer.py) for a single chunk.

    The AI reviewer compares the legacy source with the migrated Python and
    checks for semantic correctness, missing edge cases, and style issues.
    It does NOT run the code — that is Layer 3's job.
    """

    issues_found: int = 0
    """Total number of issues the AI flagged."""

    critical_issues: list[str] = Field(default_factory=list)
    """
    Issues that must be fixed before approval, e.g.:
      ['Interest calculation uses integer division — loses cents']
    """

    warnings: list[str] = Field(default_factory=list)
    """
    Non-blocking observations, e.g.:
      ['Consider extracting magic number 10000 to a named constant']
    """

    suggestions: list[str] = Field(default_factory=list)
    """Optional improvements the AI recommends but are not required."""

    ai_confidence: str = "Medium"
    """
    The LLM's self-reported confidence in its review.
    TODO (ai_reviewer.py): parse this from the structured LLM response.
    """

    raw_response: str = ""
    """
    Full raw LLM response stored for debugging and audit trail.
    Only populated when DEMO_MODE=true.
    """


# ---------------------------------------------------------------------------
# MigrationChunk
# ---------------------------------------------------------------------------

class MigrationChunk(BaseModel):
    """
    One logical unit of migrated code moving through the pipeline.

    Created by pipeline.py, enriched by Layers 1-3, then either approved or
    rejected by a human reviewer.
    """

    id: str = Field(default_factory=lambda: f"chunk-{uuid.uuid4().hex[:8]}")
    """Unique chunk identifier."""

    name: str
    """
    Human-readable name, derived from the COBOL SECTION/PARAGRAPH name.
    e.g. 'CALC-INTEREST-SECTION', 'VALIDATE-ACCOUNT-PARA'
    """

    source_file: str = ""
    """Original filename this chunk was extracted from, e.g. 'interest.cbl'."""

    start_line: int = 0
    """1-indexed start line of this chunk within source_file."""

    end_line: int = 0
    """1-indexed end line (inclusive) of this chunk within source_file."""

    source_code: str = ""
    """Original legacy source code for this chunk."""

    migrated_code: str = ""
    """
    AI-generated Python (or target language) code.
    TODO (pipeline.py / ai_reviewer.py): populate this after LLM generation.
    """

    diff: str = ""
    """
    Unified diff between source_code and migrated_code for the approval UI.
    TODO (pipeline.py): generate with difflib.unified_diff after migration.
    """

    risk_level: RiskLevel = RiskLevel.MEDIUM
    """Inherited from Layer 0 risk scorer for this chunk's source lines."""

    status: ChunkStatus = ChunkStatus.PENDING
    """Current lifecycle status — updated by pipeline.py."""

    retry_count: int = 0
    """How many times this chunk has been regenerated after a failed review."""

    test_results: list[TestResult] = Field(default_factory=list)
    """All test results from Layer 3. Empty until tests run."""

    static_analysis: Optional[StaticAnalysisResult] = None
    """Layer 1 result. None until static analysis runs."""

    ai_review: Optional[AIReviewResult] = None
    """Layer 2 result. None until AI review runs."""

    class Config:
        use_enum_values = True
